# Generated by Django 6.0.4 on 2026-04-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_descricao_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
